### ISSUE TITLE
J/Psi prototype

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#1]
Create a prototype of the J/Psi character, for reference see attached picture.
To make animations easier later on, we decided not to include the mouth of the particle.
<img width="230" alt="J:Psi_sketch" src="https://user-images.githubusercontent.com/69592687/97800810-95172380-1c38-11eb-9cff-7aa21155524a.png">

**Comment by wa12rior** [comment]
I've added prototype to the repo. It's in sample scene.

**Comment by wa12rior** [comment]
We need only animations.
