### ISSUE TITLE
Electrons with tiny jetpacks

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#100]
We don't need to implement the jetpacks but I think their cool.

**Comment by sarahgaiser** [comment]
This is our 100th issue! We might not be making a lot of progress but at least we have a lot of work 🤣

**Comment by Layfully** [comment]
![obraz](https://user-images.githubusercontent.com/15947565/130126057-46177d1a-3beb-433f-bc96-c75a10a44156.png)
