### ISSUE TITLE
PNN Breaking News letters/sign

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#102]
We need to decide if we want to have a sign saying "PNN Breaking News" or letters (similar to the particle descriptions in the trailer).

**Comment by Layfully** [comment]
![obraz](https://user-images.githubusercontent.com/15947565/126663726-491b58c0-e8ba-4bb4-9468-523b2b589ad9.png)
We have 3D letters and they can also be scaled on on one axis to imitate 2D text

**Comment by Layfully** [comment]
I will close this issue. You can reopen it if needed.
