### ISSUE TITLE
1923 Photon

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#105]

**Comment by sarahgaiser** [comment]
https://www.britannica.com/science/quantum-mechanics-physics/Einstein-and-the-photoelectric-effect

**Comment by s6nadavi** [comment]
Today, we are having a look at the discovery of the photon. This particle describes the quantised nature of light. When talking about light one usually means the light a human being can see. But a more general term that can be used is 'electromagnetic radiation', which describes the whole electromagnetic spectrum. The photon, which is also known as the exchange particle of the electromagnetic force, was discovered by non-other than Albert Einstein himself. And it was the proof of the quantisation of in form of photons that got him the Nobel prize in 1921.
Let's follow along with his thought process.
The basic idea of the experimental setup can be imagined as follows: A metal surface is exposed to monochromatic radiation (radiation that has only one colour/wavelength) and above a certain frequency. If one connects the metal surface to a circuit one can detect a current. Meaning that electrons flow out of the metal plate, which can also be viewed as a cathode, onto the positively charged anode. This process creates an electric potential between the metal plate and the anode. This phenomenon is known as the photoelectric effect, but what does this tell us about the photon? 
Well, Einstein made two observations that are crucial to correlate the incoming light to particles.
1. The energy of the emitted photons depends on the light frequency and not on how much light is incident on the metal surface. 
2. As soon as the light hits the metal plate you can instantaneously measure the electrons. There is no time delay between incoming radiation and the emission of electrons. 

These two assumptions tell us that light must consist out of tiny corpuscles (the photons) and these can only be absorbed as a whole and not partially, which results in the emission of electrons.

**Comment by sarahgaiser** [comment]
looks great to me! I'll find an image to go along with this

**Comment by sarahgaiser** [comment]
![photoeffect](https://user-images.githubusercontent.com/69592687/122579094-db4cb600-d054-11eb-80c5-280f314825a6.jpeg)

**Comment by s6nadavi** [comment]
Nice, thank you :)
