### ISSUE TITLE
1932 Neutron

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#106]

**Comment by sarahgaiser** [comment]
![Chadwick_Neutron_Discovery](https://user-images.githubusercontent.com/69592687/120085275-00de4380-c0d7-11eb-9b22-e5b560db4289.png)

**Comment by sarahgaiser** [comment]
James Chadwick
9Be + 4He (α) → 12C + 1n

**Comment by s6nadavi** [comment]
Today we are going to learn about the discovery of the neutron, which together with the proton, forms the atomic nucleus.  It was discovered by James Chadwick in 1932, at a time where nobody expected its existence. Let's start with the conduction of the experiment.
What Chadwick did, was to shoot alpha-particles from a radioactive source onto a Beryllium target. Through the interaction of the alpha-particles with the Beryllium, this experiment resulted in radiation that was emitted behind the beryllium target. Chadwick examined this radiation and found out it is electrically neutral. Hence, he initially suggested that it consists of photons, which just were discovered in the recent past. However, by having a closer look he noticed that the resulting radiation was very high in energy and could penetrate materials too easily, to be made up of photons. 
To learn more about the unknown radiation Chadwick in collaboration with Irène and Frédéric Joliot-Curie directed the radiation onto a paraffin target followed by an ionisation chamber. This chamber was usually used to detect charged particles by them ionising the gas or liquid inside the chamber. Hence, the neutral radiation should not have had an effect. However, they did observe positively charged protons inside the ionisation chamber. This observation lead them to the conclusion that the neutral radiation must have forced the protons out of the paraffin. Moreover, that this radiation must be made up of particles that are around the same mass as the protons and neutrally charged. 
This kind of particle is what we know as a neutron today.
