### ISSUE TITLE
1956 Electron Neutrino

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#109]

**Comment by s6nadavi** [comment]
https://www.wikiwand.com/en/Electron_neutrino

https://icecube.wisc.edu/neutrino-history/1956/01/1956-first-discovery-of-the-neutrino-by-an-experiment/

https://www.radioactivity.eu.com/site/pages/Neutrino_Discovery.htm

**Comment by s6nadavi** [comment]
The particle we are talking about today is the electron neutrino. Its existence was already theoretically predicted in 1930. However, it took more than 20 years until the electron neutrino was discovered by Clyde Cowan and Frederick Reines.
Let's have a closer look at the experimental setup. The two physicists first made use of a nuclear reactor. It enabled the team to have access to a high number of neutrinos per second and per square centimetres. The actual proof for the neutrinos was supposed to happen in a tank filled with cadmium chloride. It was expected that the neutrinos would interact with the liquid. By this interaction, a neutron and a positron would be created for every neutrino. The positron would then create two photons in the following reaction. However, the liquid inside the tank was also highly efficient in absorbing the created neutrons. Anytime a neutron would be absorbed, a photon ray would be emitted. 
The setup was arranged in such a way, that a photon from the reaction of the neutron with cadmium would be detected a few microseconds later than the photon created by the positron.
In total, they managed to collect evidence for 3 neutrinos per hour in their setup after a few months and published their results in July 1956.

**Comment by s6nadavi** [comment]
https://neutrino-history.in2p3.fr/experimental-discovery/

![reinesdet](https://user-images.githubusercontent.com/73640699/126814347-56f10a06-0653-4ada-895d-0b84134c581b.jpg)

I couldn't find any high res picture of he setup :/

**Comment by s6nadavi** [comment]
![1](https://user-images.githubusercontent.com/73640699/126814747-20b4ff9c-0eeb-40ca-b9d8-64424d8659b9.png)
![2](https://user-images.githubusercontent.com/73640699/126814762-02897340-8833-40d7-8d5c-caa795cec516.png)

I tried my best with canva.. :D

**Comment by Ursuss21** [comment]
![PhysicsFriday19_1](https://user-images.githubusercontent.com/44650304/126835333-4b5a2eb3-5f59-4aa8-8e74-278553eeba55.png)
![PhysicsFriday19_2](https://user-images.githubusercontent.com/44650304/126835336-8947ff5f-0b18-47fc-af37-f00a1dbc0aa0.png)
![PhysicsFriday19_3](https://user-images.githubusercontent.com/44650304/126835338-f6b4719c-8d76-442b-a363-310561b3c26f.png)
![PhysicsFriday19_4](https://user-images.githubusercontent.com/44650304/126835339-c97f2ed6-7161-48ef-be80-d565d15c1a5d.png)
![PhysicsFriday19_5](https://user-images.githubusercontent.com/44650304/126835342-2bf88e98-26ea-4936-bf86-18d28838c95c.png)
![PhysicsFriday19_6](https://user-images.githubusercontent.com/44650304/126835344-2da5a02f-b404-4b48-be43-a34bf09178e9.png)

I've created some additional slides with the text you provided @s6nadavi. Hope that's okay 😃

**Comment by s6nadavi** [comment]
That was great, thank you very much :)
