### ISSUE TITLE
Lepton Storage Room

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#11]
Assets needed in lepton storage room:

- [x] electron
- [x] positron
<img width="200" alt="electronPositron" src="https://user-images.githubusercontent.com/69592687/97807199-c5be8380-1c5f-11eb-839b-b4e52bc70020.png">

- [x]  shelves (here inspired by Pixar movie "Inside out", imagine filled with electrons or positrons)
<img width="100" alt="shelves" src="https://user-images.githubusercontent.com/69592687/97807303-59904f80-1c60-11eb-8a5c-8d9182be0cc1.png">

- [ ] storage room door

**Comment by s6nadavi** [comment]
Not sure if it's an asset, but we would also need a door outside the storage room, which we will probably also show in the news segment in scene 1...
Maybe something like that? 

![bank_door](https://user-images.githubusercontent.com/73640699/98438701-3c3e0400-20ec-11eb-9876-ae4162726271.jpg)

**Comment by sarahgaiser** [comment]
> Maybe something like that?

yes, that's exactly what I imagined. Not sure though if it belongs to the list of assets or if it's part of the background.
