### ISSUE TITLE
Voice over news speaker

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#121]

**Comment by PSSteinmann** [comment]
1 Test Draft of the news speaker audio. Should the clip be either faster or slower ? 
[jpsi_news.zip](https://github.com/JPsiInVR/organisation/files/6489831/jpsi_news.zip)

**Comment by s6nadavi** [comment]
@PSSteinmann 
I think the speed and the tone of your speech sound great! There were just a few parts that are indistinct for someone who does not know the text by heart. :D
These were "**stop removing**...the leptons  "**are in** ...desperate need" 
Other than that I think it's very nice :)

**Comment by PSSteinmann** [comment]
[jpsi_news2.zip](https://github.com/JPsiInVR/organisation/files/6823636/jpsi_news2.zip)
New Version
