### ISSUE TITLE
HUMANS & ELECTROMAGNETIC FORCE

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#124]
Focus on the fact that light is an electromagnetic wave (many people don't know that). 
Explain a bit how eyes work (this is what most people know).

**Comment by tristen-shields** [comment]
Electromagnetism is one of the "fundamental forces" of the universe (along with gravity and the strong and weak nuclear forces). The electromagnetic force has to do with electrically charged particles, and as the name implies, it is the force that is responsible for electric and magnetic interactions, as well as electric fields and magnetic fields and electromagnetic waves such as light. In 1820, Danish physicist Hans Christian Orsted noticed that a magnetic compass needle could be influenced by an electric current. This inspired French physicist Andre-Marie Ampere to create the mathematics to describe the magnetic forces between two current-carrying conductors (Ampere's Law). In 1831, English scientist Michael Faraday discovered that an electric current could be induced by a magnetic field, and also discovered the concept of 'fields' to describe electromagnetic interactions. This led Scottish scientist James Clark Maxwell to create a set of four equations to describe Faraday's research, finally completing a unified theory of electricity and magnetism. Through our eyes, we can see some electromagnetic waves (referred to as visible light) as long as it is in a certain range of wavelengths. Different colors also are a result of different EM wavelengths. Over the past century, we have used electromagnetism to power our homes and buildings with electricity. This is done through creating electric currents by spinning magnets around wires in turbines and generators. Electromagnetism is responsible for the lighting in our homes, as well as anything electric we use (appliances, phones, computers, etc.) We also use waves from the EM spectrum in medicine(x-rays to scan human skeletons for injuries) and in communication (radio waves to carry sound). 

This is very wordy, feel free to split it up in multiple tweets or edit where needed 👍
