### ISSUE TITLE
BEES & POLARIZATION

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#125]
After they know what light is, we can tell them how do we characterize electromagnetic waves: amplitude, frequency and polarization.
We humans just detect amplitude (through intensity and frequency through colors), but bees can also "see" polarization.

**Comment by tristen-shields** [comment]
![image](https://user-images.githubusercontent.com/85568869/122675948-d0576a00-d1a9-11eb-8801-252f2e0a3ff4.jpeg)![image](https://user-images.githubusercontent.com/85568869/122675954-d6e5e180-d1a9-11eb-90fb-4326ddee5e4b.jpeg)![image](https://user-images.githubusercontent.com/85568869/122675959-dc432c00-d1a9-11eb-85ca-68ae576a41a8.jpeg)![image](https://user-images.githubusercontent.com/85568869/122675973-e533fd80-d1a9-11eb-936d-81ce113c32c6.jpeg)![image](https://user-images.githubusercontent.com/85568869/122675976-e8c78480-d1a9-11eb-831d-f18602b34b91.jpeg)
![image](https://user-images.githubusercontent.com/85568869/122676025-085ead00-d1aa-11eb-818e-390cb64e51ad.jpeg)
