### ISSUE TITLE
BIRDS & MAGNETIC FIELD

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#126]
We can use this to explain that electric force and magnetic force are particular manifestations of the same thing: the electromagnetic force.
Electric charge/Moving electric charge (which is what happens on Earth's core)

**Comment by tristen-shields** [comment]
![image](https://user-images.githubusercontent.com/85568869/123478379-5f5eea80-d5cd-11eb-9d2e-934076171d66.jpeg)![image](https://user-images.githubusercontent.com/85568869/123478391-638b0800-d5cd-11eb-8c7e-8ca4fbc72c8e.jpeg)![image](https://user-images.githubusercontent.com/85568869/123478405-684fbc00-d5cd-11eb-8a59-cf48b39ee82f.jpeg)![image](https://user-images.githubusercontent.com/85568869/123478418-6d147000-d5cd-11eb-9ed9-c294b8744db2.jpeg)![image](https://user-images.githubusercontent.com/85568869/123478462-7ac9f580-d5cd-11eb-8f82-e89ad65aed79.jpeg)
