### ISSUE TITLE
Particle Discoveries Intro

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#127]
We are starting a new series for Physics Fridays! 
It's going to be about particle discoveries. You are going to learn about which experiments and techniques were used to find particles and which challenges the scientists faced. 
Some of the regarding particles you already got to know in our series about the Standard Model of Particle Physics. We are going to talk about the quark and lepton discoveries, for example. But we are also going to have a look at discoveries of composed particles like the proton and neutron. 
But before we dive into all the physics, let's talk about the concept of discovering a particle. More specifically the concept of doing physics experiments. The workflow usually consists of three basic steps (?): 

- Having a theory, hypothesis, that predicts a particle or some physical phenomenon that could exist
- thinking about how you can prove this existence/claim _whatever I dunno_ 
- executing the experiment probably several times, collecting sufficient data and comparing the outcome with the expectation _(hoping for the best ^^)_

You will see that most of the discoveries in this series followed a similar scheme in their research. As a teaser, this graphic shows you all the discoveries you will learn about in the course of our new series! Stay tuned.

**Comment by s6nadavi** [comment]
_Does somebody know, if we can simply post graphics like that on instagram?_ 

![Timeline_New](https://user-images.githubusercontent.com/73640699/119874441-e6b13380-bf25-11eb-9761-708e4cbb7dd0.png)

https://cds.cern.ch/record/2665175

**Comment by Ursuss21** [comment]
I'll redraw that later today ;)

**Comment by sarahgaiser** [comment]
We are starting a new series for Physics Fridays!
It's going to be about particle discoveries. You will learn all about the experiments and techniques the scientists used and which challenges they faced during the process.
Some of the particles you might already know from our series about the Standard Model of Particle Physics, the electron or the charm quark for example. In this series, we will also have a look at composed particles like the proton and neutron and find out how they have been discovered.

Before we dive into all the physics, let's talk about the concept of scientific experiments. If you break it down, the workflow usually consists of three basic steps:
1) Setting up a hypothesis that predicts a particle or some physical phenomenon: This hypothesis might come from some observations that you've made or in the case of particle physics might arise from theoretical physics. 
2) Thinking about ways to test your hypothesis: If you set up a theory or hypothesis in any scientific field, it is very important to make sure that there are ways to prove your theory.
3) Executing the experiment: Probably, you will need to do this step several times, collecting sufficient data and comparing the outcome with the expectation ( always hoping for the best ^^).

You will see that the discoveries in this series all followed a similar scheme. To give you a little sneak peak, this graphic shows all the discoveries we are going to cover in our new series. Stay tuned!

**Comment by Ursuss21** [comment]
![PhysicsFriday13](https://user-images.githubusercontent.com/44650304/120026979-1da14b00-bff3-11eb-94b1-a3c6d8198ec4.jpeg)
