### ISSUE TITLE
HUMANS & SOUND

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#129]
A topic to explore the classical mechanics of waves. We should explain how sound is connected with mathematical functions (for example).

**Comment by s6nadavi** [comment]
source: https://www.uio.no/studier/emner/matnat/math/nedlagte-emner/MAT-INF2360/v16/kompendiet/applinalgpythonchap1and2.pdf

**Comment by tristen-shields** [comment]
![image](https://user-images.githubusercontent.com/85568869/124399391-20294b80-dce9-11eb-8781-10e4370e98b9.jpeg)![image](https://user-images.githubusercontent.com/85568869/124399392-23bcd280-dce9-11eb-94a4-97a09043cd55.jpeg)![image](https://user-images.githubusercontent.com/85568869/124399394-261f2c80-dce9-11eb-9568-5fc784767995.jpeg)![image](https://user-images.githubusercontent.com/85568869/124399397-29b2b380-dce9-11eb-8c6a-dd8e5ad30447.jpeg)![image](https://user-images.githubusercontent.com/85568869/124399399-2dded100-dce9-11eb-801f-c35cbc16e9e4.jpeg)![image](https://user-images.githubusercontent.com/85568869/124399403-31725800-dce9-11eb-9338-b0795bd43835.jpeg)
