### ISSUE TITLE
NATURE & FOURIER SERIES

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#130]
A topic that explains the physical meaning of the Fourier series and their occurrence in nature.

**Comment by s6nadavi** [comment]
source: https://www.youtube.com/watch?v=Y9pYHDSxc7g

**Comment by tristen-shields** [comment]
![image](https://user-images.githubusercontent.com/85568869/126069845-cebd4602-badf-4aef-adfe-9b48771e0953.jpeg)![image](https://user-images.githubusercontent.com/85568869/126069848-bbb97a42-d1fd-4e83-8205-3bcf28b5cdf5.jpeg)![image](https://user-images.githubusercontent.com/85568869/126069852-8eed0a95-baae-4b4a-a40e-8dea8db0bfc7.jpeg)![image](https://user-images.githubusercontent.com/85568869/126069855-16468624-24b4-4882-92b3-8e98bc1aaf0f.jpeg)![image](https://user-images.githubusercontent.com/85568869/126069860-afc5dba3-55bc-45e7-91b8-e0c4f047df2b.jpeg)![image](https://user-images.githubusercontent.com/85568869/126069867-771bd254-4ee2-4395-905e-21593a836e97.jpeg)
