### ISSUE TITLE
WALES & SOUND

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#132]
A post that touches on the system of echolocation.

**Comment by tristen-shields** [comment]
![image](https://user-images.githubusercontent.com/85568869/128640612-2aed15f4-4749-4e96-88fd-8a13c54816c3.jpeg)![image](https://user-images.githubusercontent.com/85568869/128640614-beb107c3-301b-4b9d-85e6-5b74ae273688.jpeg)![image](https://user-images.githubusercontent.com/85568869/128640620-ce8a3145-0081-499a-85b2-e31535c07001.jpeg)![image](https://user-images.githubusercontent.com/85568869/128640625-65e37d6b-5588-4834-b416-90811de6dfac.jpeg)![image](https://user-images.githubusercontent.com/85568869/128640627-c8bef2cd-29d6-40be-beaf-35c034410391.jpeg)
