### ISSUE TITLE
MARINE LIFE & GRAVITY

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#133]
A post that discusses the relationship between the Moon and the ocean tides.

**Comment by tristen-shields** [comment]
![image](https://user-images.githubusercontent.com/85568869/132139478-d7ef3c2e-1937-4506-915e-3247c4fe056e.png)![image](https://user-images.githubusercontent.com/85568869/132139483-0e1b1586-9c81-4fcc-b090-8cbfddcfb6a5.png)![image](https://user-images.githubusercontent.com/85568869/132139487-ed724abe-6489-4ecc-8f51-17ccc861db79.png)![image](https://user-images.githubusercontent.com/85568869/132139490-0c2702a4-af0c-4220-800d-7ea66752aa40.png)![image](https://user-images.githubusercontent.com/85568869/132139498-2946712f-ea09-474c-8d91-c65578aa0bea.png)![image](https://user-images.githubusercontent.com/85568869/132139505-c2171c65-c215-4ad9-be18-4f0a0bc68fb8.png)
