### ISSUE TITLE
ATOMS & STRONG NUCLEAR FORCE

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#134]

**Comment by tristen-shields** [comment]
![image](https://user-images.githubusercontent.com/85568869/130368315-614efb32-386c-4947-b636-16920656d9f3.png)![image](https://user-images.githubusercontent.com/85568869/130368340-beb9a95b-f0e4-4df5-b1a6-50fb7690228d.png)![image](https://user-images.githubusercontent.com/85568869/130368346-075c0119-ff31-4036-8f1d-371a19bdb46e.png)![image](https://user-images.githubusercontent.com/85568869/130368353-88b8e842-7a3a-45bf-a074-933260d93374.png)![image](https://user-images.githubusercontent.com/85568869/130368356-bdc2c189-c89e-4348-8b90-e64a19e901f1.png)![image](https://user-images.githubusercontent.com/85568869/130368360-de2a3eb4-a415-40ae-b16d-858c6cc7a6ae.png)![image](https://user-images.githubusercontent.com/85568869/130368364-cd2de7fb-47bc-4e96-98a2-5bde24c57105.png)
