### ISSUE TITLE
FASER Part 2

### ISSUE THREAD

**Issue by melbiel** [JPsiInVR/organisation#136]
Last week we spoke a bit about the FASER experiment and the interesting hypothetical particles.
Today we try to explain one of these particle, the dark photon.
The dark photon is a so called hidden sector particle, and is proposed to be a force carrier which is connected to dark matter. The hidden sector or also known as dark sector, is a collection of hypthetical yet-unobserved particles and their quantum fields. The idea behind the dark photon is that it can couple very weakly to electrically charged particles, via kinetic mixing with the normal photon. The proposal of this particle bases on the existence of dark matter. We know that there is matter that we can not see, because we see gravitational effects in the universe, that can not be explained by the known Standard Model matter alone. Dark photons could be part of the non gravitational interaction between dark matter particles and Standard Model particles.

**Comment by Ursuss21** [comment]
![wedex21_1](https://user-images.githubusercontent.com/44650304/134405723-c96087e0-3aec-44cf-999f-4cc46e004a5c.png)
![wedex21_2](https://user-images.githubusercontent.com/44650304/134405726-1b17f48b-e22c-4162-8002-f0a02a394c9d.png)
![wedex21_3](https://user-images.githubusercontent.com/44650304/134405728-4bd8264d-d766-4770-b9e1-46292b53f3c0.png)
![wedex21_4](https://user-images.githubusercontent.com/44650304/134405730-2101022b-7c1f-4a20-96eb-31fc2c71d03a.png)
![wedex21_5](https://user-images.githubusercontent.com/44650304/134405731-b74af174-d652-430a-8890-0795bb412d49.png)
