### ISSUE TITLE
SALT & ICE 

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#138]

**Comment by tristen-shields** [comment]
![image](https://user-images.githubusercontent.com/85568869/140615774-e5fafa10-29ca-4251-9069-e2f629460597.png)![image](https://user-images.githubusercontent.com/85568869/140615777-2c76db1e-2b41-496a-a12c-3d3f2652fdc2.png)![image](https://user-images.githubusercontent.com/85568869/140615788-086ceaae-ef8c-4122-a716-e7a3019e6160.png)![image](https://user-images.githubusercontent.com/85568869/140615791-8bf118a8-38a2-4f24-af4c-55f53dd6f5c6.png)![image](https://user-images.githubusercontent.com/85568869/140615795-d74213c9-950f-42bd-8da5-7c0015ef6847.png)
