### ISSUE TITLE
Proton prototype

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#2]
Create a prototype of the proton character, for reference see attached picture.
To make animations easier later on, we decided not to include the mouth of the particle.
<img width="116" alt="Proton_sketch" src="https://user-images.githubusercontent.com/69592687/97800974-b75d7100-1c39-11eb-931e-36ee20c81858.png">

**Comment by Layfully** [comment]
![Proton](https://user-images.githubusercontent.com/15947565/100877606-4c59c100-34a9-11eb-8700-268fb08ef35c.png)
