### ISSUE TITLE
Selection of links to particle physics information

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#26]
Create a list of useful links to (popular) physics webpages that contain information on particle physics, the Standard Model, particle accelerators and detectors.

**Comment by s6nadavi** [comment]
**Learn more about the world of particle physics:** 

Particle Physics at CERN
https://home.cern/science/physics

Particle Physics at ALTAS
https://atlas.cern/discover/physics

The Standard Model of Particle Physics
https://home.cern/science/physics/standard-model




**Get to know the Laboratories that discovered Jpsi:**

SLAC - Stanford Linear Accelerator Center

Main Facts
https://www6.slac.stanford.edu/about/slac-overview

History of SLAC
https://www6.slac.stanford.edu/about/slac-history


BNL - Brookhaven National Laboratory

Main Facts
https://www.bnl.gov/about/

History of discoveries at BNL
https://www.bnl.gov/about/history/discoveries.php




**Want to stay up to date?
Then check these links with lots of news about the particle physics world and current research topics:**

Symmetry Magazine
https://www.symmetrymagazine.org/

Quanta Magazine
https://www.quantamagazine.org/tag/particle-physics/

Nature Research
https://www.nature.com/subjects/particle-physics

Fermilab at Work
https://news.fnal.gov/fermilab-at-work/

CMS
https://cms.cern/


**Still curious? Test your knowledge with this interactive quiz:**

https://particleadventure.org/
