### ISSUE TITLE
Summary of JUNO project

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#27]
Write a short summary of the JUNO project for the webpage.

@wa12rior Could you add the descriptions that Naomi wrote down in the comments below to the link section on the webpage?

**Comment by s6nadavi** [comment]
Maybe something like:

J/psi UNder Observation (JUNO) is a visualization of the J/psi particle discovery in virtual reality (VR). The JUNO adventure introduces the viewer to the exciting world of a particle and intends to give insight into the principles of research in particle physics.
Follow the J/psi along its virtual journey and get to know the tiny particles that build the matter surrounding us.

Or should it summarize the plotlines and content more specifically?

**Comment by s6nadavi** [comment]
We can probably also add parts of the APS abstract

**Comment by s6nadavi** [comment]
J/ψ UNder Observation (JUNO) is a visualization of the J/ψ particle discovery in virtual reality (VR). 
The JUNO adventure introduces you to the exciting world of particle physics and can be enjoyed using the Google Cardboard coupled with any smartphone. It intends to give insight into the groundbreaking physics experiments involved in the J/ψ discovery in 1974 and highlights their different approaches.
In a second story line, you can experiencet the subatomic particles being protagonists themselves, as they question the social order of their world. 
Join J/ψ and its friends along in their virtual revolution and get to know the tiny particles that build the matter surrounding us!

**Comment by sarahgaiser** [comment]
I've added some suggestions to your comment, @s6nadavi 😄

**Comment by s6nadavi** [comment]
Yes, that sounds great. Thank you ! :)
