### ISSUE TITLE
Neutron prototype

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#3]
Create a prototype of the neutron character, for reference see attached picture.
To make animations easier later on, we decided not to include the mouth of the particle.

<img width="124" alt="Neutron_sketch" src="https://user-images.githubusercontent.com/69592687/97801044-35ba1300-1c3a-11eb-8396-560fffdeaf4f.png">

**Comment by Layfully** [comment]
![Neutron](https://user-images.githubusercontent.com/15947565/100877409-0866bc00-34a9-11eb-8e56-cb6d63aa46f4.png)
