### ISSUE TITLE
Professional camera

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#31]
Build model of camera from news scene in Blender.

<img width="100" alt="professionalCamera" src="https://user-images.githubusercontent.com/69592687/97806469-0ae0b680-1c5c-11eb-85cb-d7421e572568.png">

**Comment by sarahgaiser** [comment]
![NewsRoomExport](https://user-images.githubusercontent.com/69592687/103461342-f1bcba80-4d1d-11eb-8b38-5d9b8ab4b664.jpg)

**Comment by Layfully** [comment]
![obraz](https://user-images.githubusercontent.com/15947565/126664511-c68dabe0-0636-4a0e-9751-154c066704e0.png)
This is a model @MPogwizd created. I think we can close this one :)
