### ISSUE TITLE
Tripod

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#33]
Create model of tripod for cameras in news room.

<img width="100" alt="tripod" src="https://user-images.githubusercontent.com/69592687/97806775-9d358a00-1c5d-11eb-851b-c0f2ffdc438d.png">

**Comment by sarahgaiser** [comment]
![NewsRoomExport](https://user-images.githubusercontent.com/69592687/103461342-f1bcba80-4d1d-11eb-8b38-5d9b8ab4b664.jpg)

**Comment by Layfully** [comment]
![obraz](https://user-images.githubusercontent.com/15947565/111880849-066c2e80-89ae-11eb-8846-f9efe70c8b02.png)
