### ISSUE TITLE
Particle News Speaker

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#37]
Create a model of the particle that is presenting the news.

**Comment by sarahgaiser** [comment]
![NewsRoomExport](https://user-images.githubusercontent.com/69592687/103461342-f1bcba80-4d1d-11eb-8b38-5d9b8ab4b664.jpg)

**Comment by PSSteinmann** [comment]
Sooo, I can't upload .blend files here, so I zipped it. This should do it more or less
[newsdude.zip](https://github.com/JPsiInVR/organisation/files/6493276/newsdude.zip)

**Comment by PSSteinmann** [comment]
![image](https://user-images.githubusercontent.com/77334148/118478417-23a04d80-b710-11eb-8056-e0efe383199d.png)
Thats the Basic Draft

**Comment by Layfully** [comment]
I've imported it to unity 
![obraz](https://user-images.githubusercontent.com/15947565/126711033-99744e94-d138-4d7e-a041-016f0b936bab.png)
I've noticed that it's hard to make him visible without making him look like he's levitating. Should we give him something to stand on?
