### ISSUE TITLE
Up quark prototype

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#4]
Create a prototype of the up quark character, for reference see attached picture.
Up and down quark should be of same shape and size. They are supposed to be smaller than charm, strange, top and bottom quark.
<img width="123" alt="Up_sketch" src="https://user-images.githubusercontent.com/69592687/97801116-b1b45b00-1c3a-11eb-9615-503b135c743d.png">

**Comment by Layfully** [comment]
![UpQuark](https://user-images.githubusercontent.com/15947565/100877109-9d1cea00-34a8-11eb-91d6-0f24de429735.png)
