### ISSUE TITLE
Gravitation

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#45]

**Comment by s6nadavi** [comment]
Do you guys also feel like we have neglected a very important force that interacts with our bodies all the time and that defines life on earth as we know it? 
You're totally right, we haven't talked about Gravitation yet! Gravitation describes the attractive force between two masses. The heavier the mass the stronger is also its gravitational pull. This explains, why our large planet does such a good job at keeping us down to earth. 

The gravitational constant is about 9,807 m/s² on earth. And as you might know this is quite large compared to the moon's gravitational constant of just 1,62 m/s², for example. (source of constants: Wikipedia)
