### ISSUE TITLE
Higgs boson and field

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#46]

**Comment by s6nadavi** [comment]
Here's a great clip about the Higgs boson and the basic idea of the Higgs field:

https://www.youtube.com/watch?v=IElHgJG5Fe4

**Comment by sarahgaiser** [comment]
![higgs](https://user-images.githubusercontent.com/69592687/115010502-cb2a2600-9ead-11eb-9403-a08922386947.jpeg)

**Comment by s6nadavi** [comment]
Today, we want to introduce you to the final element of the Standard Model: The Higgs Boson. It was discovered in 2012 at the ATLAS and CMS experiments. It has a mass of 125 GeV and is very different from all the other force-carrying Bosons. It is said that the Higgs Boson is responsible for a mechanism that makes all particles acquire their mass. 

If you want to learn more about the basic idea of this mechanism and about the Higgs field that is correlated to the Higgs Boson, check out this great conversation:

https://www.youtube.com/watch?v=IElHgJG5Fe4
