### ISSUE TITLE
Weak interaction

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#47]

**Comment by s6nadavi** [comment]
Here's a nice video that introduces the viewer to the concept of fields and force-carrying bosons. It is also a sums up the previous post about the elementary particles as well as the other interactions mentioned before. 

https://www.youtube.com/watch?v=X9otDixAtFw

**Comment by sarahgaiser** [comment]
![weakWW](https://user-images.githubusercontent.com/69592687/115007775-a2546180-9eaa-11eb-87e3-34e5eb28e66f.jpeg)

**Comment by s6nadavi** [comment]
Let's have a look at another fundamental force of the Standard Model of Particle Physics: The weak interaction. 
It is responsible for things like nuclear decay and nuclear fusion. One of the mediating bosons of this interaction is the W-Boson. 

Do you feel like you want to learn more about the concept of fields and force-carrying bosons? 
Then check out this video: 

https://www.youtube.com/watch?v=X9otDixAtFw
