### ISSUE TITLE
Strong interaction

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#48]
We need to talk about strong interaction before we can move on to Higgs and the summary of the Standard Model.
@s6nadavi can you take care of this? I will provide some graphic

**Comment by s6nadavi** [comment]
You probably already heard about atoms, right? They are bound together to build molecules. But did you ever wonder what makes up an atom? 
Well, every atom is a bound system of a nucleus that is orbited by electrons. This nucleus is again a composed structure, that consists of neutrons and protons. 
The neutrons and protons are 'glued' together by the strong nuclear force, which is another fundamental force of the Standard Model. The mediating particles of this interaction are called gluons.

**Comment by sarahgaiser** [comment]
![strong_ww](https://user-images.githubusercontent.com/69592687/116685067-136b3d00-a9b2-11eb-8c9f-166b7655896f.jpeg)
