### ISSUE TITLE
Charm & Strange quarks

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#51]

**Comment by s6nadavi** [comment]
Today we are going to have a look at the charm and strange quark. They belong to the second generation of quarks and are therefore slightly heavier than the first generation up- and down quarks. Apart form the mass difference they have the same properties as the first generation quarks in terms of charge and spin.
Interestingly the hero of our story, the J/Psi meson, consists of a charm-quark and a charm anti-quark.

But...are you wondering what a Meson actually is? Then check out this video about baryons and meson and how they are formed by elementary particles: 

https://www.youtube.com/watch?v=xW6s2xHGcxs

**Comment by sarahgaiser** [comment]
![charm_and_strange](https://user-images.githubusercontent.com/69592687/113404311-3fda6c00-93a8-11eb-99da-d6e70cebd233.jpeg)
