### ISSUE TITLE
Neutrinos

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#53]

**Comment by sarahgaiser** [comment]
Today we will learn more about uncharged leptons, so called neutrinos. Neutrinos are a fascinating topic and we could go on and on talking about them. However, we will keep it short today and let the people from Fermilab explain everything you ever wanted to know about Neutrinos. They created this amazing video series called "Even Bananas" which has an episode dedicated to Neutrinos: https://www.youtube.com/watch?v=zL5p3CqXxbw

**Comment by Ursuss21** [comment]
![PhysicsFriday3](https://user-images.githubusercontent.com/44650304/111773372-5f549d80-88ae-11eb-9a6f-3f6e1f510ccc.png)
