### ISSUE TITLE
Fermilab

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#57]

**Comment by melbiel** [comment]
The main focus of the @Fermilab (Fermi National Accelerator Laboratory) is on accelerator physics. The Tevatron was the most powerful accelerator in the world, before LHC went online. It was a proton anti-proton accelerator, whose most important achievement was the discovery  1/2
of the top quark. Fermilab also hosts numerous neutrino experiments, like the Muon g-2, which measures the anomaly of the magnetic moment of the muon. 2/2
