### ISSUE TITLE
SLAC

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#58]
Maybe we should split up SLAC a little more. In general Stanford Linear Accelerator is a research facility meaning that there are several experiments located at SLAC. Also, J/Psi was discovered at SPEAR which is an old accelerator that has been replaced by SLAC.

**Comment by melbiel** [comment]
The main research focus of the @SLAClab is on particle physics, but it also covers astronomy, solid state physics and more. The main accelerator was a linear accelerator, which accelerated electrons and positrons. With over 3 km in length, it was the longest linear accelerator in the world. Notable discoveries of SLAC are the tau lepton (hence completing the three lepton families) and the quark structure of proton and neutron, using deep inelastic scattering of electrons on protons and bound neutrons. Moreover it is one of two places the J/Ψ particle was discovered. The group at SLAC, lead by Burton Richter, named it Ψ.
