### ISSUE TITLE
LHCb

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#59]

**Comment by melbiel** [comment]
The @LHCbExperiment is specialized on  physics concerning the b-meson. For example, CP violation in the interaction of b-mesons could help to explain why there is more matter in the universe than antimatter, the so-called matter-antimatter asymmetry.

**Comment by Ursuss21** [comment]
![wedex2](https://user-images.githubusercontent.com/44650304/110650161-980fbb00-81ba-11eb-888b-5638974d9ec8.png)
