### ISSUE TITLE
ATLAS

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#61]

**Comment by melbiel** [comment]
The @ATLASexperiment is the largest general purpose particle detector at the LHC. It was one of two experiments that discovered the Higgs Boson, the so-called "God Particle" and by that the last puzzle piece of the Standard Model. The next step is beyond Standard Model physics.

**Comment by melbiel** [comment]
[Gluon-gluon-fusion.pdf](https://github.com/JPsiInVR/organisation/files/6192388/Gluon-gluon-fusion.pdf)
