### ISSUE TITLE
ALICE

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#62]

**Comment by melbiel** [comment]
The @ALICEexperiment is optimized for heavy ion collisions. This allows to explore a state which is believed to have existed a fraction of a second after the Big Bang, the quark-gluon plasma.
The produced plasma had a temperature of around 5 trilllion kelvins – world record.

**Comment by melbiel** [comment]
I am open for suggestions concerning a picture

**Comment by Ursuss21** [comment]
![wedex3](https://user-images.githubusercontent.com/44650304/111442146-56c26280-8708-11eb-8ee4-41af5f9b39e5.png)
