### ISSUE TITLE
LHC

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#63]

**Comment by melbiel** [comment]
The LHC is the world largest (27 km circumference) and most powerful particle collider in the world. The collider has four beampipe crossing points, where proton or heavy ion beams collide.
The beams get accelerated by cavity resonators and kept on the circular path by magnets.

**Comment by sarahgaiser** [comment]
Maybe you could simplify the last sentence even more. I doubt that people know what a cavity resonator is :D 
Other than that I think this is great for a start!

**Comment by melbiel** [comment]
But this is how they are accelerated. I don´t think that we should leave this out of the tweet, so interested people can look it up.

**Comment by sarahgaiser** [comment]
I wouldn't leave it out either, I just think it needs some more explanation.

**Comment by melbiel** [comment]
[LHC_pic.pdf](https://github.com/JPsiInVR/organisation/files/6084115/LHC_pic.pdf)
