### ISSUE TITLE
Police particle

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#68]
![PoliceParticle](https://user-images.githubusercontent.com/69592687/111876550-863ecc80-899f-11eb-8778-d3a239b7116c.jpeg)

**Comment by sarahgaiser** [comment]
inspired by British police
![zwei-britische-polizisten-patrouillieren-in-den-strassen-von-england-tragen-erstechen-westen-b07x5x](https://user-images.githubusercontent.com/69592687/111876567-95be1580-899f-11eb-80ef-433825bb9a39.jpg)

**Comment by MPogwizd** [comment]
[Police.zip](https://github.com/JPsiInVR/organisation/files/6342061/Police.zip)
