### ISSUE TITLE
Police car

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#69]
![PoliceCar](https://user-images.githubusercontent.com/69592687/111876627-d7e75700-899f-11eb-9b5c-6ceb4e9cb7f9.jpeg)

**Comment by sarahgaiser** [comment]
![PoliceCar](https://user-images.githubusercontent.com/69592687/111876512-5d1e3c00-899f-11eb-96dd-8e5002af2dae.jpeg)

**Comment by Layfully** [comment]
We can use one of these cars:
https://assetstore.unity.com/packages/3d/vehicles/land/low-poly-police-car-pack-59458
And modify then if needed.

**Comment by MPogwizd** [comment]
[Police.zip](https://github.com/JPsiInVR/organisation/files/6342056/Police.zip)
