### ISSUE TITLE
Charm quark prototype

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#7]
Create a prototype of the charm quark character, for reference see attached picture.
Charm and strange quark should be of same shape and size. They are supposed to be bigger than up and down quark but smaller than top and bottom quark.
![charm_quark](https://user-images.githubusercontent.com/69592687/111877070-cef78500-89a1-11eb-88ef-ecb85be41700.jpeg)

**Comment by MPogwizd** [comment]
[CharmQuark_NotFinal.zip](https://github.com/JPsiInVR/organisation/files/6175970/CharmQuark_NotFinal.zip)

**Comment by MPogwizd** [comment]
[CharmQuark.zip](https://github.com/JPsiInVR/organisation/files/6249485/CharmQuark.zip)
