### ISSUE TITLE
Muon g-2 experiment

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#82]
Some content on the recent discovery at the muon g-2 experiment at Fermilab:

Let's start with general Information:

https://www.youtube.com/watch?v=UckuqHDB08I

And then we could post the video of Fermilab about the recent discovery and their meaning:

https://www.youtube.com/watch?v=ZjnK5exNhZ0

**Comment by s6nadavi** [comment]
Do you need some additional text, Robert ?

**Comment by Ursuss21** [comment]
I guess I could prepare something based on the videos.

**Comment by s6nadavi** [comment]
Okay, otherwise just let me know if you need anything. I don't think you have to 'say' much, since everything important is mentioned in the videos.  

But maybe you can introduce this special topic by saying something like... 

_We've already told you about the Standard Model of particle physics and you also met a few of its elements... BUT: There is some very recent and exciting news about the SM theory... 
The muon g-2 Experiment has found evidence that causes serious doubt about the rules of the particle world as we know them right now!_

or something similar... :D

**Comment by Ursuss21** [comment]
Okay, then I no longer need to prepare something based on the video xD Thanks!
