### ISSUE TITLE
Belle/Belle2

### ISSUE THREAD

**Issue by melbiel** [JPsiInVR/organisation#85]

**Comment by melbiel** [comment]
The @belle2collab is a detector located at the collision point of an asymmetric-energy electron-positron collider. Its predecessor the belle detector, was designed for detection of B-mesons.
The belle detector observed CP-violation in the neutral B-meson system and found a possible tetraquark candidate – a particle containing four quarks. It was updated to the Belle2 detector to collect 50 times more data.
The logo of Belle shows multiple aspects of the experiment. It investigates the collision of electrons and positrons (e ɘ), the B in Belle breaks the symmetry between el - le (matter and anitmatter) and B-mesons contain b-quarks, which were formerly known as beauty-quarks.

**Comment by Ursuss21** [comment]
![wedex9](https://user-images.githubusercontent.com/44650304/116385449-17b02280-a819-11eb-9b5d-8f8f44207748.png)
