### ISSUE TITLE
BaBar

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#88]

**Comment by Ursuss21** [comment]
![wedex16_1](https://user-images.githubusercontent.com/44650304/127400299-32d42c9c-cfec-4e26-845b-af9c0be77f26.png)
![wedex16_2](https://user-images.githubusercontent.com/44650304/127400303-6beca435-1007-4e52-a714-24fc2a8edea8.png)
![wedex16_3](https://user-images.githubusercontent.com/44650304/127400306-5ace4367-d743-4089-a94c-1e396144f09e.png)
![wedex16_4](https://user-images.githubusercontent.com/44650304/127400309-7518f43d-c00a-426a-b27a-b76eb301aa8e.png)
![wedex16_5](https://user-images.githubusercontent.com/44650304/127400319-9da8cdf1-e61d-40ee-b321-4ce17932057c.png)
![wedex16_6](https://user-images.githubusercontent.com/44650304/127400321-49b5deb1-ed3a-4441-ab0b-cf1b86203c94.png)
