### ISSUE TITLE
IceCube

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#89]
Another very cool neutrino experiment at Antarctica.

**Comment by melbiel** [comment]
The IceCube Neutrino Observatory is looking for high energy neutrinos in the TeV range. As we know, neutrinos are rarely interacting with matter (via the weak-interaction), thus an enourmous detection volume is needed. In case of IceCube, it is a 1 km3 large ice cube. When neutrinos hit the water molecules in the ice, they can produce fast electrons, muons or taus, which produce Cherenkov radiation. The Cherenkov radiation is detected by thousand photomultiplier tubes. They are located in holes in the ice, that have a deepth between 1450 and 2450 meters. This makes IceCube the largest neutrino telescope in the world.
