### ISSUE TITLE
COMPASS

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#91]
https://home.cern/science/experiments/compass

**Comment by melbiel** [comment]
The Common Muon and Proton Apparatus for Structure and Spectroscopy (COMPASS) is a 60 meter long fixed-target mulipurpose experiment located at CERN´s Super Proton Synchrotron (SPS). The main goals of the experiment are to investigate nucleon spin structure and the spectrum of particles formed by quarks and gluons, so called hadron spectroscopy.
The studies of the nucleon spin structure focus on the origin of spin in general, and the individual contributions of quarks and gluons within the nucleons. This is investigated by using beams of muons and pions on a polarized target. The experiment is also looking for exotic particles, like glueballs, which are made completely of gluons. The AMBER experiment (Apparatus for Meson and Baryon Experimental Research) is the upcoming succesor of COMPASS.
