### ISSUE TITLE
DUNE

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#92]
https://www.dunescience.org/

**Comment by melbiel** [comment]
@DUNEScience (Deep Underground Neutrino Experiment) will be an experiment studying neutrinos and their properties. For this, an intense neutrino beam is produced at Fermilab and send 1300 kilometers (800 miles) through the Earth to strike a 70-kiloton volume of liquid argon acting as a detector. This detector will be 1.5 kilometers below the surface. The primary goals are to measure neutrino oscillation parameters and to determine the neutrino mass hierarchy. Furthermore it looks for neutrinos beyond the known three ones. Up until now the experiment is still under construction, the first beam is planned for 2026 and in 2027 the experiment is planned to be operational.

**Comment by Ursuss21** [comment]
![wedex18_1](https://user-images.githubusercontent.com/44650304/129960719-01a3db68-6e53-4147-9d78-4328e86d94aa.png)
![wedex18_2](https://user-images.githubusercontent.com/44650304/129960721-eea6f961-8936-47ac-8131-c4bdab00e3fd.png)
![wedex18_3](https://user-images.githubusercontent.com/44650304/129960723-dd546664-e037-4880-a80f-f8f7bbeb3d84.png)
![wedex18_4](https://user-images.githubusercontent.com/44650304/129960725-cb29b671-921b-4ca5-b4e4-608f4994970a.png)
