### ISSUE TITLE
GlueX

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#94]
http://www.gluex.org/

**Comment by melbiel** [comment]
The @Glue_X experiment is located at the @JLab_News accelerator, which we already covered. It is looking into the nature of confinement in quantum chromodynamics. It describes the phenomenon that color-charged particles cannot be isolated, hence we only see mesons, baryons and exotic hadrons like tetraquark states. GlueX is specifically searching for exotic mesons, hadrons with the baryon number equal to zero.  These particles can be produced by scattering a photon on a nucleon. To identify the mesonic states more easily, linear polarized photons are used.

**Comment by Ursuss21** [comment]
![wedex19_1](https://user-images.githubusercontent.com/44650304/131818604-9361600a-0e9b-4663-b1a4-bdb3e543575f.png)
![wedex19_2](https://user-images.githubusercontent.com/44650304/131818612-58d1ed2c-9311-47c6-8443-872656871ac2.png)
![wedex19_3](https://user-images.githubusercontent.com/44650304/131818616-88809cb8-05b6-46a9-bfb0-743020226158.png)
![wedex19_4](https://user-images.githubusercontent.com/44650304/131818626-101d73a0-574a-4624-901b-cb99d57cfcd4.png)

Sorry for being late, I totally forgot about the post yesterday!
