### ISSUE TITLE
FASER - introduction

### ISSUE THREAD

**Issue by melbiel** [JPsiInVR/organisation#96]

**Comment by melbiel** [comment]
The @FASERexperiment (ForwArd Search ExpeRiment) is a particle experiment at the LHC. It is designed to search for new elementary particles as the dark photon or axion-like particles, and to study high-energy neutrinos. These particles are hypothetical weakly interacting particles with low masses, which are proposed to describe physics beyond the standard model. If you are interested in these, look out for the next wednesday tweet.

**Comment by Ursuss21** [comment]
![wedex20_4](https://user-images.githubusercontent.com/44650304/133494161-44b0cdce-4ebc-4278-90a0-6d7ca7a0ceb2.png)
![wedex20_1](https://user-images.githubusercontent.com/44650304/133494163-443b01b4-9b81-4d9e-af18-48c0863ceaad.png)
![wedex20_2](https://user-images.githubusercontent.com/44650304/133494165-75575b9c-a3f0-4f4c-b0de-15f11f892538.png)
![wedex20_3](https://user-images.githubusercontent.com/44650304/133494166-2756b0e7-6b4f-4ce8-a286-7cf7524a7ba0.png)
